version: v1alpha1

# Settings that apply on at the project level.
project:
  # Indicate the root of the runme project. "." means that
  # the project root directory will be used.
  root: "."
  # If true, the project root will be searched upwards starting from "dir".
  # If found, the repo root will be used as the project root.
  find_repo_upward: true
  ignore:
    - "node_modules"
    - ".venv"
  disable_gitignore: false

  # List of dotenv files to load.
  env:
    use_system_env: false
    sources:
      - ".env"
      - ".env.local"

server:
  # Also unix:///path/to/file.sock is supported.
  address: localhost:7998
  tls:
    enabled: true
    # If not specified, default paths will be used.
    # cert_file: "/path/to/cert.pem"
    # key_file: "/path/to/key.pem"

log:
  enabled: false
  path: "/var/log/runme.log"
